---
- name: enable NFS server
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: use_nfs_server

- name: enable NFS client
  service:
    name: nfs-client.target
    state: started
    enabled: yes
