---
- name: check if a cluster is already running
  shell: "docker ps | grep -sq 'ceph/daemon'"
  register: ceph_health
  changed_when: false
  failed_when: false

- include: checks.yml
  when:
    - ceph_health.rc != 0
    - not osd_containerized_deployment_with_kv

- name: check if it is Atomic host
  stat: path=/run/ostree-booted
  register: stat_ostree

- name: set fact for using Atomic host
  set_fact:
      is_atomic: '{{ stat_ostree.stat.exists }}'

- include: pre_requisite.yml

- include: "{{ playbook_dir }}/roles/ceph-common/tasks/docker/fetch_image.yml"
  vars:
    ceph_docker_username: '{{ ceph_osd_docker_username}}'
    ceph_docker_imagename: '{{ ceph_osd_docker_imagename}}'

# NOTE (jimcurtis): dirs_permissions.yml must precede fetch_configs.yml
# because it creates the directories needed by the latter.
- include: dirs_permissions.yml

- include: fetch_configs.yml
  when: not osd_containerized_deployment_with_kv

- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: start_docker_osd.yml
