---
- include: pre_requisite.yml
- include: "{{ playbook_dir }}/roles/ceph-common/tasks/docker/fetch_image.yml"
  vars:
    ceph_docker_username: '{{ ceph_restapi_docker_username}}'
    ceph_docker_imagename: '{{ ceph_restapi_docker_imagename}}'
- include: dirs_permissions.yml
- include: fetch_configs.yml
- include: start_docker_restapi.yml
